pipeline:
  name: build-microservices
  identifier: buildmicroservices
  projectIdentifier: microservicessampleapp
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: HarnessGit
        repoName: microservices-sample
        build: <+input>
  stages:
    - stage:
        name: build-and-push
        identifier: buildandpush
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: Harness_Docker
                    repo: sriniganga/service-one
                    tags:
                      - latest
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_2
                  identifier: BuildAndPushDockerRegistry_2
                  spec:
                    connectorRef: Harness_Docker
                    repo: sriniganga/service-two
                    tags:
                      - latest
