pipeline:
  name: build-microservices
  identifier: buildmicroservices
  projectIdentifier: microservicessampleapp
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: HarnessGit
        repoName: microservices-sample
        build: <+input>
  stages:
    - stage:
        name: build-and-push
        identifier: buildandpush
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build Java Project
                  identifier: Build_Java_Project
                  spec:
                    connectorRef: Harness_Docker
                    image: maven:3.8-jdk-8
                    shell: Sh
                    command: mvn clean install
                  description: Build Java Project
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: Harness_Docker
                    repo: sriniganga/service-one
                    tags:
                      - latest
                    dockerfile: service-one/src/main/docker/Dockerfile
                    context: service-one/target
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_2
                  identifier: BuildAndPushDockerRegistry_2
                  spec:
                    connectorRef: Harness_Docker
                    repo: sriniganga/service-two
                    tags:
                      - latest
                    dockerfile: service-two/src/main/docker/Dockerfile
                    context: service-two/target
